////////////////////////////////////////////////////////////////////////
// Class:       ElasticLikeVertex
// Module Type: analyzer
// File:        ElasticLikeVertex_module.cc
//
// Generated at Mon Jul 29 09:41:14 2019 by Hunter Sullivan using artmod
// from cetpkgsupport v1_10_02.
////////////////////////////////////////////////////////////////////////

#include "art/Framework/Core/EDAnalyzer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "art/Utilities/InputTag.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"


class ElasticLikeVertex;

class ElasticLikeVertex : public art::EDAnalyzer {
public:
  explicit ElasticLikeVertex(fhicl::ParameterSet const & p);
  // The destructor generated by the compiler is fine for classes
  // without bare pointers or other resource use.

  // Plugins should not be copied or assigned.
  ElasticLikeVertex(ElasticLikeVertex const &) = delete;
  ElasticLikeVertex(ElasticLikeVertex &&) = delete;
  ElasticLikeVertex & operator = (ElasticLikeVertex const &) = delete;
  ElasticLikeVertex & operator = (ElasticLikeVertex &&) = delete;

  // Required functions.
  void analyze(art::Event const & e) override;

  // Selected optional functions.
  void beginJob() override;
  void beginRun(art::Run const & r) override;
  void beginSubRun(art::SubRun const & sr) override;
  void endJob() override;
  void endRun(art::Run const & r) override;
  void endSubRun(art::SubRun const & sr) override;
  void reconfigure(fhicl::ParameterSet const & p) override;
  void respondToCloseInputFile(art::FileBlock const & fb) override;
  void respondToCloseOutputFiles(art::FileBlock const & fb) override;
  void respondToOpenInputFile(art::FileBlock const & fb) override;
  void respondToOpenOutputFiles(art::FileBlock const & fb) override;

private:

  // Declare member data here.

};


ElasticLikeVertex::ElasticLikeVertex(fhicl::ParameterSet const & p)
  :
  EDAnalyzer(p)  // ,
 // More initializers here.
{}

void ElasticLikeVertex::analyze(art::Event const & e)
{
  // Implementation of required member function here.
}

void ElasticLikeVertex::beginJob()
{
  // Implementation of optional member function here.
}

void ElasticLikeVertex::beginRun(art::Run const & r)
{
  // Implementation of optional member function here.
}

void ElasticLikeVertex::beginSubRun(art::SubRun const & sr)
{
  // Implementation of optional member function here.
}

void ElasticLikeVertex::endJob()
{
  // Implementation of optional member function here.
}

void ElasticLikeVertex::endRun(art::Run const & r)
{
  // Implementation of optional member function here.
}

void ElasticLikeVertex::endSubRun(art::SubRun const & sr)
{
  // Implementation of optional member function here.
}

void ElasticLikeVertex::reconfigure(fhicl::ParameterSet const & p)
{
  // Implementation of optional member function here.
}

void ElasticLikeVertex::respondToCloseInputFile(art::FileBlock const & fb)
{
  // Implementation of optional member function here.
}

void ElasticLikeVertex::respondToCloseOutputFiles(art::FileBlock const & fb)
{
  // Implementation of optional member function here.
}

void ElasticLikeVertex::respondToOpenInputFile(art::FileBlock const & fb)
{
  // Implementation of optional member function here.
}

void ElasticLikeVertex::respondToOpenOutputFiles(art::FileBlock const & fb)
{
  // Implementation of optional member function here.
}

DEFINE_ART_MODULE(ElasticLikeVertex)
